server:
  address: 0.0.0.0
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  application:
    name: yxchatbot
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yx_chatbot?useSSL=false&serverTimezone=UTC&useSSL=true&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  redis:
    host: 127.0.0.1
    port: 6379
    database: 2
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        max-wait: 100ms
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: org.example.entity # 别名扫描包
logging:
  level:
    org.example: debug
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: common-producer-group
jwt:
  secret-key: YWJjZGVmMDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWYwMTIzNDU2Nzg5YWJjZGVmMDEyMzQ1Njc4OQ==
  expiration: 36000000
  refresh-expiration: 6048000000
api:
  key: 734440e045bbd1aeaba5292d62786a5d.pdq8ik04sXo1tygr

minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: uploads
  publicUrl: http://localhost:9000